SELECT * FROM EMP_YOOLIM;

SELECT * FROM DEPT_YOOLIM;

--EX01

SELECT DEPT.DEPTNO, DEPT.DNAME, EMP.EMPNO, EMP.ENAME, EMP.SAL
FROM DEPT_YOOLIM DEPT, EMP_YOOLIM EMP
WHERE EMP.DEPTNO = DEPT.DEPTNO
AND SAL > 2000
ORDER BY DEPT.DEPTNO, EMP.EMPNO;

SELECT DEPT.DEPTNO, DEPT.DNAME, AVG(EMP.SAL) AS AVG_SAL, MAX(EMP.SAL) AS MAX_SAL, MIN(EMP.SAL) AS MIN_SAL, COUNT(EMP.EMPNO) AS CNT
FROM DEPT_YOOLIM DEPT, EMP_YOOLIM EMP
WHERE DEPT.DEPTNO = EMP.DEPTNO
GROUP BY DEPT.DEPTNO, DEPT.DNAME
--HAVING DEPT.DEPTNO = EMP.DEPTNO --> 왜 HAVING은 안되징...
;

--EX04

SELECT DEPT.DEPTNO, DEPT.DNAME, EMP.EMPNO, EMP.ENAME, EMP.MGR, EMP.SAL, EMP.DEPTNO, SALGRADE.LOSAL, SALGRADE.HISAL, SALGRADE.GRADE, EMP2.EMPNO AS MGR_EMPNO, EMP2.ENAME AS MGR_ENAME
FROM DEPT_YOOLIM DEPT, EMP_YOOLIM EMP, SALGRADE_YOOLIM SALGRADE, EMP_YOOLIM EMP2
WHERE DEPT.DEPTNO = EMP.DEPTNO(+)
AND EMP.SAL BETWEEN SALGRADE.LOSAL(+) AND SALGRADE.HISAL(+)
AND EMP2.EMPNO(+) = EMP.MGR
ORDER BY DEPT.DEPTNO, EMP.EMPNO;